### ISSUE TITLE
Change name in `package-lock.json` as well.

### ISSUE THREAD

**Issue by WeeJeWel** [5alidz/change-package-name#2]

**Comment by 5alidz** [comment]
These package-lock files can be huge and I wouldn't say I like the idea of this simple script loading potentially megabytes into memory to change the name.

Also, the lock file is auto-generated by `npm install` and I think we shouldn't really touch it 😂

but please tell me how you are using this package or what issue you encounter after running the script and npm found out the package name mismatch
